Repository harsh-9in/Blogger, pull requests merged in 2020-09, with the labels that each got.

#118 logo_added
  mysite/Logo_RITIKSONI/1 - Copy (2).svg
  mysite/Logo_RITIKSONI/1 - Copy.favicon
  mysite/Logo_RITIKSONI/1.png
  mysite/Logo_RITIKSONI/Black-Texture - Copy (2).svg
  mysite/Logo_RITIKSONI/Black-Texture - Copy.favicon
  mysite/Logo_RITIKSONI/Black-Texture.png
  mysite/Logo_RITIKSONI/image (25) - Copy.favicon
  mysite/Logo_RITIKSONI/image (25) - Copy.png
  mysite/Logo_RITIKSONI/image (25) - Copy.svg
Labels: CH20

#123 Added View Count + Read TIme
  mysite/blog/migrations/0001_initial.py
  mysite/blog/migrations/0002_auto_20200824_0201.py
  mysite/blog/migrations/0002_auto_20200825_2231.py
  mysite/blog/models.py
  mysite/blog/static/blog/main.css
  mysite/blog/static/blog/viewicon.png
  mysite/blog/templates/blog/home.html
  mysite/blog/templates/blog/post_detail.html
  mysite/blog/utils.py
  mysite/blog/views.py
  mysite/db.sqlite3
  mysite/staticfiles/img/viewicon.png
Labels: CH20, hard

#141 Added the Community Page
  static/css/style_communitypage.css
  static/images/logo-transparent.png
  templates/communitypage.html
  templates/footer.html
  templates/header.html
Labels: CH20, medium
