Repository harsh-9in/Blogger, pull requests merged in 2020-08, with the labels that each got.

#27 PR_Templates.md & feature_request_template.md
  .github/ISSUE_TEMPLATE/Features_request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/Pull_request_Template.md
Labels: CH20, easy

#37 Created the wireframe for the Home Page
  mysite/staticfiles/Wireframes/Home.png
Labels: CH20, medium

#54 Added the profile editing functionality.
  mysite/mysite/urls.py
  mysite/users/forms.py
  mysite/users/templates/user/editProfile.html
  mysite/users/templates/user/profile.html
  mysite/users/views.py
Labels: CH20, hard

#64 This is the WireFrame for the Homepage .
  mysite/HPUWPNG.PNG
Labels: CH20, medium

#63 Dashboard Wireframe Done
  mysite/staticfiles/dashboard ui_nooras/DashboardNew.png
Labels: CH20, medium

#59 Showing profile for normal users
  mysite/blog/templates/blog/home.html
  mysite/blog/urls.py
  mysite/blog/views.py
  mysite/db.sqlite3
  mysite/media/profile_pics/1476068871520.jpg
  mysite/media/profile_pics/1476068871520_aOEkPtH.jpg
  mysite/users/templates/user/login.html
  mysite/users/templates/user/profile.html
  mysite/users/views.py
Labels: CH20, easy

#65 Bllogger logo added
  mysite/logo_shraddhavp/Blogger logo.png
  mysite/logo_shraddhavp/Blogger logo1.png
Labels: CH20, easy

#67 LogoDesign
  mysite/logo_neha/blogger_logo.png
Labels: CH20, easy

#83 Community Page Wireframe
  mysite/Communitypage _Wireframe.PNG
Labels: CH20, UI, medium

#50 Created the wireframe for the Community Page
  mysite/wireframes/Community.png
Labels: CH20, medium

#58 Updated the README.md file
  README.md
Labels: CH20, ReadMe

#103 added homepage UI
  mysite/staticfiles/homepage ui_Akshi149/Homepage_UI.png
Labels: CH20, UI, hard

#101 Created the UI for the community (expanded) page
  mysite/staticfiles/community(expanded)_ui_yash/Community - Home UI.png
Labels: CH20, UI, hard

#102 Added Community Page UI Design
  mysite/staticfiles/communitypage_ui_AdityaAshvin.JPG
Labels: CH20, UI, hard

#109 Dashboard UI for Blogger site
  mysite/staticfiles/dashboard ui_nooras/DashboardUIFinal.png
Labels: CH20, UI, hard
